development:
  provider: 'AWS'       # required
  aws_access_key_id:      'AKIAIT47VZNUWYIXSPSA'       # required
  aws_secret_access_key:  '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'       # required
  bucket:

production:
   provider:               'AWS'       # required
   aws_access_key_id:      'AKIAIT47VZNUWYIXSPSA'       # required
   aws_secret_access_key:  '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'       # required
   bucket:                 'wotdashboard'

