class CreateReports < ActiveRecord::Migration
  def change
    create_table :reports do |t|
      t.date :starts_date
      t.date :ends_date
      t.string :title
      t.text :note
      t.string :data
      t.references :user
      t.references :graphic
      t.boolean :is_autogenerated, :default => true, :null => false

      t.timestamps
    end
  end
end
